### ISSUE TITLE
I want to help you

### ISSUE THREAD

**Issue by FrankScarlet** [anpho/ShadowsocksUWP#1]
It is my first time to create an issue. 
I really need a shadowsocksUWP because my cellphone is Lumia 950. I want to use Instagram and Steam Community on my phone...
I search on GitHub and find this repository. I am learing c-sharp. I hope I can help you soon.
Could you give me some instructions on how to build it ? Should I look into [ss-win](https://github.com/shadowsocks/shadowsocks-windows)?

**Comment by anphorea** [comment]
As far as I know this project has been suspended because of lacking of VPN provider privilege which I believe Microsoft should offer or at least offer under approval.
if you want to contribute / build uwp version by yourself, maybe you'd try another solution like setup some vpn servers that microsoft windows supported ( didn't work for me )

**Comment by FrankScarlet** [comment]
Okay. I get it.
